---
# tasks file for k8s-cluster-create

# ==================== INITIALIZE KUBERNETES CLUSTER ====================
- name: Initialize Kubernetes cluster with kubeadm
  command: >
    kubeadm init 
    --pod-network-cidr={{ pod_network_cidr }} 
  args:
    creates: /etc/kubernetes/admin.conf
  become: true
  register: kubeadm_init

- name: Create .kube directory for the root user
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0700'

- name: Copy Kubernetes config for root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
  become: true

# ==================== UNTAINT MASTER NODE (SINGLE NODE SETUP) ====================
- name: Untaint master node to allow pod scheduling
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  ignore_errors: yes
  when: kubeadm_init.changed and untaint_master
